import crypto from 'node:crypto';
import jwt from 'jsonwebtoken';
import {createRemoteJWKSet,jwtVerify} from 'jose';
import {User,LoginCode} from './models.js';

const providers={
 google:{authorize:'https://accounts.google.com/o/oauth2/v2/auth',token:'https://oauth2.googleapis.com/token',jwks:'https://www.googleapis.com/oauth2/v3/certs',issuer:'https://accounts.google.com',clientId:()=>process.env.GOOGLE_CLIENT_ID,clientSecret:()=>process.env.GOOGLE_CLIENT_SECRET},
 microsoft:{authorize:()=>`https://login.microsoftonline.com/${process.env.MICROSOFT_TENANT_ID||'common'}/oauth2/v2.0/authorize`,token:()=>`https://login.microsoftonline.com/${process.env.MICROSOFT_TENANT_ID||'common'}/oauth2/v2.0/token`,jwks:'https://login.microsoftonline.com/common/discovery/v2.0/keys',clientId:()=>process.env.MICROSOFT_CLIENT_ID,clientSecret:()=>process.env.MICROSOFT_CLIENT_SECRET}
};
const callbackUrl=p=>`${process.env.PUBLIC_API_URL||'http://localhost:3333'}/api/auth/${p}/callback`,webUrl=()=>process.env.WEB_URL?.split(',')[0]||'http://localhost:5173',hash=v=>crypto.createHash('sha256').update(v).digest('hex');

export function startOAuth(provider){return(req,res)=>{const p=providers[provider];if(!p.clientId()||!p.clientSecret())return res.redirect(`${webUrl()}/?oauth_error=provider_not_configured`);const state=jwt.sign({provider,nonce:crypto.randomUUID()},process.env.JWT_SECRET,{expiresIn:'10m',issuer:'nova-commerce-oauth'}),url=new URL(typeof p.authorize==='function'?p.authorize():p.authorize);url.search=new URLSearchParams({client_id:p.clientId(),redirect_uri:callbackUrl(provider),response_type:'code',scope:'openid email profile',state,prompt:'select_account'});res.redirect(url.toString());};}

export function finishOAuth(provider){return async(req,res,next)=>{try{const p=providers[provider],state=jwt.verify(String(req.query.state||''),process.env.JWT_SECRET,{issuer:'nova-commerce-oauth'});if(state.provider!==provider||!req.query.code)throw new Error('Retorno OAuth inválido.');const body=new URLSearchParams({client_id:p.clientId(),client_secret:p.clientSecret(),code:String(req.query.code),grant_type:'authorization_code',redirect_uri:callbackUrl(provider)}),response=await fetch(typeof p.token==='function'?p.token():p.token,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!response.ok)throw new Error('O provedor recusou a autenticação.');const tokens=await response.json(),options={audience:p.clientId()};if(provider==='google')options.issuer=p.issuer;const{payload}=await jwtVerify(tokens.id_token,createRemoteJWKSet(new URL(p.jwks)),options);if(provider==='microsoft'&&!String(payload.iss||'').startsWith('https://login.microsoftonline.com/'))throw new Error('Emissor Microsoft inválido.');const email=String(payload.email||payload.preferred_username||'').toLowerCase();if(!email||payload.email_verified===false)throw new Error('O provedor não confirmou um e-mail válido.');const providerId=String(payload.sub);let user=await User.findOne({'providers.provider':provider,'providers.providerId':providerId});if(!user){user=await User.findOne({email});if(user){if(!user.providers.some(x=>x.provider===provider))user.providers.push({provider,providerId,email});user.emailVerifiedAt=user.emailVerifiedAt||new Date();await user.save();}else user=await User.create({name:String(payload.name||email.split('@')[0]),email,emailVerifiedAt:new Date(),providers:[{provider,providerId,email}]});}const rawCode=crypto.randomBytes(32).toString('base64url');await LoginCode.create({codeHash:hash(rawCode),user:user._id,expiresAt:new Date(Date.now()+120000)});res.redirect(`${webUrl()}/?oauth_code=${encodeURIComponent(rawCode)}`);}catch(error){next(error);}};}

export async function exchangeOAuthCode(rawCode){const record=await LoginCode.findOne({codeHash:hash(rawCode),usedAt:null,expiresAt:{$gt:new Date()}}).populate('user');if(!record)throw Object.assign(new Error('Código de acesso inválido ou expirado.'),{status:401});record.usedAt=new Date();await record.save();return record.user;}
