import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Search,ShoppingBag,User,Menu,X,Heart,Star,Truck,ShieldCheck,RotateCcw,ArrowRight,Minus,Plus,SlidersHorizontal,Package,LayoutDashboard,ShoppingCart,Users,Tag,TrendingUp,LogOut,ChevronRight,CheckCircle2}from'lucide-react';
import'./styles.css';

const products=[
{id:1,name:'Tênis Orbit Runner',cat:'Tênis',brand:'NOVA',price:429.9,old:529.9,color:'Preto',badge:'Best-seller',rating:4.9,stock:18,img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85'},
{id:2,name:'Mochila Urban Core',cat:'Acessórios',brand:'Atelier',price:289.9,color:'Preto',badge:'Novo',rating:4.8,stock:9,img:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85'},
{id:3,name:'Relógio Meridian',cat:'Acessórios',brand:'Meridian',price:599.9,old:699.9,color:'Prata',badge:'-14%',rating:4.7,stock:6,img:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=85'},
{id:4,name:'Headphone Studio One',cat:'Tecnologia',brand:'Sonic',price:749.9,color:'Bege',badge:'Exclusivo',rating:4.9,stock:12,img:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85'},
{id:5,name:'Óculos Horizon',cat:'Acessórios',brand:'Horizon',price:239.9,color:'Marrom',badge:'Novo',rating:4.6,stock:22,img:'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=85'},
{id:6,name:'Câmera Pocket Classic',cat:'Tecnologia',brand:'RetroLab',price:899.9,color:'Preto',badge:'Últimas unidades',rating:4.8,stock:3,img:'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=900&q=85'}];
const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

function App(){
 const[view,setView]=useState('home'),[cart,setCart]=useState([]),[query,setQuery]=useState(''),[cat,setCat]=useState('Todos'),[sort,setSort]=useState('featured'),[menu,setMenu]=useState(false),[toast,setToast]=useState(''),[selected,setSelected]=useState(null),[coupon,setCoupon]=useState('');
 const list=useMemo(()=>products.filter(p=>(cat==='Todos'||p.cat===cat)&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:b.rating-a.rating),[query,cat,sort]);
 const add=p=>{setCart(c=>{let e=c.find(x=>x.id===p.id);return e?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});setToast('Produto adicionado ao carrinho');setTimeout(()=>setToast(''),2200)};
 const total=cart.reduce((s,p)=>s+p.price*p.qty,0), count=cart.reduce((s,p)=>s+p.qty,0);
 const nav=v=>{setView(v);setMenu(false);scrollTo(0,0)};
 return <div className="app">
  <div className="topbar">Frete grátis acima de R$ 299 <span>•</span> 10% OFF na primeira compra: <b>BEMVINDO10</b></div>
  <header><button className="icon mobile" onClick={()=>setMenu(!menu)} aria-label="Menu"><Menu/></button><button className="brand" onClick={()=>nav('home')}>NOVA<span>.</span></button>
   <nav className={menu?'open':''}><button onClick={()=>nav('home')}>Início</button><button onClick={()=>nav('catalog')}>Novidades</button><button onClick={()=>{setCat('Tênis');nav('catalog')}}>Tênis</button><button onClick={()=>{setCat('Acessórios');nav('catalog')}}>Acessórios</button><button onClick={()=>nav('catalog')} className="sale">Sale</button></nav>
   <div className="actions"><button className="icon" onClick={()=>nav('catalog')} aria-label="Buscar"><Search/></button><button className="icon" onClick={()=>nav('account')} aria-label="Conta"><User/></button><button className="icon bag" onClick={()=>nav('cart')} aria-label="Carrinho"><ShoppingBag/><i>{count}</i></button></div>
  </header>
  {view==='home'&&<Home nav={nav} add={add}/>} {view==='catalog'&&<Catalog list={list} query={query} setQuery={setQuery} cat={cat} setCat={setCat} sort={sort} setSort={setSort} add={add} setSelected={setSelected}/>} {view==='cart'&&<Cart cart={cart} setCart={setCart} total={total} coupon={coupon} setCoupon={setCoupon} nav={nav}/>} {view==='account'&&<Account nav={nav}/>} {view==='admin'&&<Admin/>}
  <Footer nav={nav}/>{toast&&<div className="toast"><CheckCircle2/> {toast}</div>}{selected&&<ProductModal p={selected} close={()=>setSelected(null)} add={add}/>} 
 </div>
}
function Home({nav,add}){return <main><section className="hero"><div className="hero-copy"><small>COLEÇÃO ESSENTIALS 2026</small><h1>Design que acompanha o seu ritmo.</h1><p>Peças essenciais, materiais premium e tecnologia para uma rotina em movimento.</p><div><button className="primary" onClick={()=>nav('catalog')}>Explorar coleção <ArrowRight/></button><button className="link" onClick={()=>nav('catalog')}>Ver lançamentos</button></div><div className="hero-stats"><span><b>30 dias</b> para trocar</span><span><b>4,9/5</b> por clientes</span><span><b>Compra</b> protegida</span></div></div><div className="hero-image"><img src={products[0].img} alt="Tênis vermelho da coleção Orbit"/><span className="float-card">ORBIT RUNNER<small>Performance urbana</small></span></div></section>
<section className="benefits"><div><Truck/><span><b>Frete grátis</b><small>Em compras acima de R$ 299</small></span></div><div><ShieldCheck/><span><b>Pagamento seguro</b><small>Seus dados sempre protegidos</small></span></div><div><RotateCcw/><span><b>Troca simplificada</b><small>Até 30 dias após a compra</small></span></div></section>
<section className="section"><div className="section-head"><div><small>CURADORIA NOVA</small><h2>Escolhas que fazem diferença.</h2></div><button className="link" onClick={()=>nav('catalog')}>Ver todos <ArrowRight/></button></div><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} p={p} add={add}/>)}</div></section>
<section className="editorial"><div><small>NOVA MEMBERS</small><h2>Seu estilo.<br/>Suas vantagens.</h2><p>Entre para o clube e tenha acesso antecipado, benefícios exclusivos e recomendações personalizadas.</p><button className="light" onClick={()=>nav('account')}>Criar minha conta <ArrowRight/></button></div><div className="editorial-numbers"><span><b>10%</b>OFF na primeira compra</span><span><b>2x</b>Pontos no mês de aniversário</span></div></section></main>}
function ProductCard({p,add,setSelected}){return <article className="product"><div className="photo" onClick={()=>setSelected&&setSelected(p)}><img src={p.img} alt={p.name}/><em>{p.badge}</em><button className="wish" aria-label="Favoritar"><Heart/></button><button className="quick" onClick={e=>{e.stopPropagation();add(p)}}>Adicionar</button></div><small>{p.brand} · {p.cat}</small><h3>{p.name}</h3><div className="price"><b>{money(p.price)}</b>{p.old&&<del>{money(p.old)}</del>}</div><div className="rating"><Star/> {p.rating} <span>({Math.round(p.rating*23)})</span></div></article>}
function Catalog({list,query,setQuery,cat,setCat,sort,setSort,add,setSelected}){return <main className="catalog section"><div className="catalog-title"><small>COLEÇÃO COMPLETA</small><h1>Encontre o seu próximo essencial.</h1><p>{list.length} produtos selecionados</p></div><div className="catalog-tools"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produtos..."/></label><div className="chips">{['Todos','Tênis','Acessórios','Tecnologia'].map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><label className="select"><SlidersHorizontal/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Mais relevantes</option><option value="low">Menor preço</option><option value="high">Maior preço</option></select></label></div><div className="product-grid">{list.map(p=><ProductCard p={p} add={add} setSelected={setSelected}/>)}</div>{!list.length&&<div className="empty"><Search/><h2>Nenhum produto encontrado</h2><button onClick={()=>{setQuery('');setCat('Todos')}}>Limpar filtros</button></div>}</main>}
function Cart({cart,setCart,total,coupon,setCoupon,nav}){const update=(id,d)=>setCart(c=>c.map(p=>p.id===id?{...p,qty:Math.max(1,p.qty+d)}:p));return <main className="cart-page section"><div className="catalog-title"><small>SEU PEDIDO</small><h1>Carrinho de compras</h1></div>{!cart.length?<div className="empty"><ShoppingBag/><h2>Seu carrinho está vazio</h2><p>Explore a coleção e encontre algo especial.</p><button className="primary" onClick={()=>nav('catalog')}>Ver produtos</button></div>:<div className="cart-layout"><div className="cart-list">{cart.map(p=><article><img src={p.img}/><div><small>{p.brand}</small><h3>{p.name}</h3><p>Cor: {p.color}</p><div className="qty"><button onClick={()=>update(p.id,-1)}><Minus/></button><span>{p.qty}</span><button onClick={()=>update(p.id,1)}><Plus/></button></div></div><div className="line-price"><b>{money(p.price*p.qty)}</b><button onClick={()=>setCart(c=>c.filter(x=>x.id!==p.id))}>Remover</button></div></article>)}</div><aside className="summary"><h2>Resumo</h2><p><span>Subtotal</span><b>{money(total)}</b></p><p><span>Frete</span><b className="green">Grátis</b></p><label>Cupom de desconto<div><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Digite seu cupom"/><button>Aplicar</button></div></label><hr/><p className="grand"><span>Total</span><b>{money(total)}</b></p><small>ou 10x de {money(total/10)} sem juros</small><button className="primary full" onClick={()=>alert('Checkout demonstrativo pronto. A próxima integração liga o gateway real.')}>Ir para o checkout <ArrowRight/></button><div className="secure"><ShieldCheck/> Ambiente seguro e criptografado</div></aside></div>}</main>}
function Account({nav}){return <main className="account-page section"><div className="account-card"><div className="account-copy"><small>NOVA MEMBERS</small><h1>Bem-vindo à sua melhor experiência de compra.</h1><p>Acompanhe pedidos, salve favoritos e receba vantagens exclusivas.</p><ul><li><CheckCircle2/> 10% OFF na primeira compra</li><li><CheckCircle2/> Histórico e rastreio de pedidos</li><li><CheckCircle2/> Lista de desejos sincronizada</li></ul></div><form onSubmit={e=>{e.preventDefault();alert('Login demonstrativo validado')}}><h2>Entrar</h2><label>E-mail<input type="email" placeholder="voce@email.com" required/></label><label>Senha<input type="password" placeholder="••••••••" required/></label><button className="primary full">Entrar</button><button type="button" className="social">Continuar com Google</button><button type="button" className="social">Continuar com Apple</button><p>Não tem conta? <button type="button">Cadastre-se</button></p><button type="button" className="admin-link" onClick={()=>nav('admin')}>Acessar demonstração administrativa</button></form></div></main>}
function Admin(){const[tab,setTab]=useState('Visão geral');return <main className="admin"><aside><button className="brand">NOVA<span>.</span><small>ADMIN</small></button>{[['Visão geral',LayoutDashboard],['Pedidos',ShoppingCart],['Produtos',Package],['Clientes',Users],['Cupons',Tag]].map(([n,I])=><button className={tab===n?'active':''} onClick={()=>setTab(n)}><I/>{n}</button>)}<button className="logout"><LogOut/>Sair</button></aside><section><div className="admin-head"><div><small>PAINEL ADMINISTRATIVO</small><h1>{tab}</h1></div><div className="avatar">ES</div></div>{tab==='Visão geral'?<><div className="metrics"><Metric title="Receita total" value="R$ 128.420" change="+18,2%"/><Metric title="Pedidos" value="1.284" change="+12,4%"/><Metric title="Ticket médio" value="R$ 314,90" change="+5,1%"/><Metric title="Conversão" value="3,8%" change="+0,6%"/></div><div className="admin-grid"><div className="chart-card"><h2>Desempenho de vendas</h2><div className="bars">{[44,58,49,72,66,82,74,91,78,94,88,100].map((v,i)=><i style={{height:v+'%'}}><span>{['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'][i]}</span></i>)}</div></div><div className="orders"><h2>Pedidos recentes</h2>{[['#10482','Marina Costa','R$ 749,90','Pago'],['#10481','Carlos Lima','R$ 429,90','Enviado'],['#10480','Ana Souza','R$ 289,90','Pendente'],['#10479','João Alves','R$ 839,80','Pago']].map(r=><div>{r.map((x,i)=><span className={i===3?'status':''}>{x}</span>)}</div>)}</div></div></>:<div className="module"><Package/><h2>Módulo de {tab}</h2><p>CRUD, filtros, paginação e ações administrativas preparados para integração com a API.</p><button className="primary">Adicionar novo</button></div>}</section></main>}
function Metric({title,value,change}){return <div><span>{title}</span><h2>{value}</h2><small><TrendingUp/>{change} este mês</small></div>}
function ProductModal({p,close,add}){return <div className="modal" onClick={close}><div onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><img src={p.img}/><section><small>{p.brand} · {p.cat}</small><h2>{p.name}</h2><div className="rating"><Star/> {p.rating} · {p.stock} em estoque</div><p>Design contemporâneo, materiais selecionados e conforto para acompanhar todos os momentos.</p><h3>{money(p.price)}</h3><label>Tamanho<div className="sizes">{['36','38','40','42'].map(s=><button>{s}</button>)}</div></label><button className="primary full" onClick={()=>{add(p);close()}}>Adicionar ao carrinho</button></section></div></div>}
function Footer({nav}){return <footer><div className="footer-main"><div><button className="brand">NOVA<span>.</span></button><p>Design essencial para uma vida em movimento.</p></div><div><b>Comprar</b><button onClick={()=>nav('catalog')}>Novidades</button><button onClick={()=>nav('catalog')}>Mais vendidos</button><button onClick={()=>nav('catalog')}>Ofertas</button></div><div><b>Ajuda</b><button>Trocas e devoluções</button><button>Entregas</button><button>Fale conosco</button></div><div><b>Newsletter</b><p>Novidades e benefícios no seu e-mail.</p><label><input placeholder="Seu melhor e-mail"/><button><ArrowRight/></button></label></div></div><div className="copyright">© 2026 NOVA Commerce. Todos os direitos reservados.<span>Privacidade · Termos · LGPD</span></div></footer>}
createRoot(document.getElementById('root')).render(<App/>);
